name: MLflow CI Pipeline

on: [push, pull_request]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run MLflow project
        run: |
          cd MLProject
          mlflow run .

      # Simpan artefak ke GitHub
      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: MLProject/mlruns/

      # Build & Push Docker Image
      - name: Build Docker image with MLflow
        run: |
          cd MLProject
          # Temukan folder model terbaru (asumsi run pertama)
          MODEL_PATH=$(find mlruns -name "model" -type d | head -n1)
          if [ -z "$MODEL_PATH" ]; then
            echo "Model not found!"
            exit 1
          fi
          mlflow models build-docker -m "$MODEL_PATH" -n credit-score-model

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag credit-score-model ${{ secrets.DOCKER_USERNAME }}/credit-score-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/credit-score-model:latest
