name: CI - MLflow Retrain

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Miniconda and create env from conda.yaml
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12
        environment-file: MLproject/conda.yaml
        activate-environment: mlflow-env

    - name: Verify env and MLflow exists
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        which python
        python --version
        pip show mlflow
        mlflow --version

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        set -e
        conda activate mlflow-env
        mlflow run MLproject -e main -P data_path=diabetes_dataset_2019_preprocessing.csv

    - name: Upload mlruns artifact
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/
