name: Retrain ML Model

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: mlflow-env
          environment-file: MLproject/conda.yaml
          python-version: 3.12

      - name: Show current directory structure
        run: |
          echo "üìÅ Current Directory Structure:"
          find . -type f -not -path "./\\.git/*" -not -path "./venv/*" -not -path "./__pycache__/*" | sort

      - name: Verify dataset existence
        run: |
          if [ ! -f "diabetes_dataset_2019_preprocessing.csv" ]; then
            echo "Dataset 'diabetes_dataset_2019_preprocessing.csv' not found in root directory"
            exit 1
          fi
          echo "Dataset found."

      - name: Install Python dependencies
        run: |
          pip install -r MLproject/requirements.txt
          pip install mlflow

      - name: Activate Conda Environment and Run Training
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE

          # Verifikasi path ke file MLproject
          if [ ! -f "MLproject/MLproject" ]; then
            echo "File MLproject (MLproject) not found!"
            exit 1
          fi

          echo "Starting MLflow training..."
          mlflow run MLproject \
            -P dataset="diabetes_dataset_2019_preprocessing.csv" \
            --env-manager=conda

          echo "Model trained successfully"

      - name: Show MLflow Run Summary
        shell: bash -l {0}
        run: |
          echo "Listing MLflow runs..."
          ls -R ./mlruns || echo "No mlruns directory found!"
